# Generated by Django 3.0.3 on 2020-05-06 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_auto_20200506_0954'),
        ('equipamentos', '0002_modulo_fotovoltaico_tier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_mod_cliente', models.IntegerField()),
                ('potencia', models.IntegerField()),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('geracao_estimada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Irradiacao_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamentos.Irradiacao')),
                ('inversor_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamentos.Inversor_fotovoltaico')),
                ('modulo_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamentos.Modulo_fotovoltaico')),
                ('nome_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente')),
            ],
        ),
    ]
