# Generated by Django 3.0.3 on 2020-05-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inversor_fotovoltaico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabricante', models.CharField(max_length=40)),
                ('modelo', models.CharField(max_length=40)),
                ('num_de_MPPT', models.IntegerField(blank=True)),
                ('corrente_max_entrada', models.DecimalField(decimal_places=1, max_digits=8)),
                ('corrente_max_curto', models.DecimalField(decimal_places=1, max_digits=8)),
                ('faixa_de_tensao_entrada_min', models.DecimalField(decimal_places=1, max_digits=8)),
                ('faixa_de_tensao_entrada_max', models.DecimalField(decimal_places=1, max_digits=8)),
                ('tensao_de_inicio', models.IntegerField(blank=True)),
                ('range_op_DC_MPPT_min', models.IntegerField(blank=True)),
                ('range_op_DC_MPPT_max', models.IntegerField(blank=True)),
                ('qtd_conexoes', models.DecimalField(decimal_places=1, max_digits=8)),
                ('pot_pico', models.IntegerField()),
                ('pot_nominal_CA', models.IntegerField(blank=True)),
                ('pot_maxima_CA', models.IntegerField(blank=True)),
                ('pot_maxima_saida_CA', models.IntegerField(blank=True)),
                ('tensao_max_CA', models.IntegerField(blank=True)),
                ('tensao_min_CA', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Irradiacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=40)),
                ('irradiacao_janeiro', models.DecimalField(decimal_places=2, max_digits=10)),
                ('irradiacao_fevereiro', models.DecimalField(decimal_places=2, max_digits=10)),
                ('irradiacao_marco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('irradiacao_abril', models.DecimalField(decimal_places=2, max_digits=10)),
                ('irradiacao_maio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('irradiacao_junho', models.DecimalField(decimal_places=2, max_digits=10)),
                ('irradiacao_julho', models.DecimalField(decimal_places=2, max_digits=10)),
                ('irradiacao_agosto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('irradiacao_setembro', models.DecimalField(decimal_places=2, max_digits=10)),
                ('irradiacao_outubro', models.DecimalField(decimal_places=2, max_digits=10)),
                ('irradiacao_novembro', models.DecimalField(decimal_places=2, max_digits=10)),
                ('irradiacao_dezembro', models.DecimalField(decimal_places=2, max_digits=10)),
                ('irradiacao_media', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Modulo_fotovoltaico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabricante', models.CharField(max_length=40)),
                ('modelo', models.CharField(max_length=40)),
                ('pot_nom_maxima', models.IntegerField()),
                ('tensao_de_operacao', models.DecimalField(decimal_places=1, max_digits=3)),
                ('corrente_de_operacao', models.DecimalField(decimal_places=1, max_digits=3)),
                ('tensao_circuito_aberto', models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=3)),
                ('corrente_de_curto_circuito', models.DecimalField(decimal_places=1, max_digits=3)),
                ('eficiencia_modulo', models.DecimalField(blank=True, decimal_places=1, max_digits=3)),
                ('fusivel', models.IntegerField(blank=True)),
                ('tolerancia_de_pot_min', models.IntegerField()),
                ('tolerancia_de_pot_max', models.IntegerField()),
                ('tipo_celula', models.CharField(choices=[('MONOCRISTALINA', 'MONOCRISTALINA'), ('POLICRISTALINA', 'POLICRISTALINA')], max_length=15)),
                ('comprimento', models.DecimalField(decimal_places=1, max_digits=8)),
                ('largura', models.DecimalField(decimal_places=1, max_digits=8)),
                ('profundidade', models.DecimalField(decimal_places=1, max_digits=8)),
                ('peso', models.DecimalField(decimal_places=1, max_digits=8)),
                ('coeficiente_de_temperatura_Pmax', models.DecimalField(decimal_places=2, max_digits=8)),
                ('coeficiente_de_temperatura_Voc', models.DecimalField(decimal_places=2, max_digits=8)),
                ('coeficiente_de_temperatura_Isc', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
