# Generated by Django 3.0.3 on 2020-05-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo_fotovoltaico',
            name='tier',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
