# Generated by Django 3.0.3 on 2020-05-04 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0002_modulo_fotovoltaico_tier'),
        ('calculadora', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultado',
            name='teste',
        ),
        migrations.AddField(
            model_name='resultado',
            name='inversor',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='equipamentos.Inversor_fotovoltaico'),
        ),
        migrations.AddField(
            model_name='resultado',
            name='modulo',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='equipamentos.Modulo_fotovoltaico'),
        ),
    ]
