# Generated by Django 3.0.3 on 2020-04-27 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=200)),
                ('cidade_cliente', models.CharField(max_length=200)),
                ('estado_cliente', models.CharField(max_length=2)),
                ('cep_cliente', models.CharField(max_length=8)),
                ('telefone', models.CharField(max_length=7)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
    ]
