# Generated by Django 3.0.3 on 2020-05-06 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20200427_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fatura',
            field=models.ImageField(blank=True, default='', null=True, upload_to='faturas_clientes'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='hora_registro',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
